#!/usr/bin/env python3
"""
build_icon_sprite.py — one <symbol> sprite from assets/icons/swaxs-icons-svg/.

The icon set is a folder of standalone .svg files (35 at the time of
writing). The count is DISCOVERED by globbing, never listed here — adding an
icon means dropping the file in and re-running this. The hub references them as
`<svg><use href="…#swaxs-reduction"/></svg>`, which needs a single document of
<symbol> elements, so this builds it:

    assets/icons/swaxs-icons-svg/*.svg   →   assets/icons/swaxs-icons-sprite.svg
                                         →   hub/templates/_icon_sprite.svg

The hub serves its OWN static folder (Flask(__name__)), so a file under
assets/ is not reachable from a hub page. Same reason tools/make_watchdog_icon
copies its PNG there, and tests/test_favicons.py checks it.

What each symbol keeps and drops:

  * the file's `viewBox` becomes the symbol's — the set is drawn on 24x24, but
    it is read off the file rather than assumed, so an odd one out still works;
  * `width`/`height` are DROPPED. A symbol must size to its <use>, and a
    hard-coded 24px would make every instance 24px whatever the CSS says;
  * `fill`, `stroke`, `stroke-width`, `stroke-linecap`, `stroke-linejoin` are
    carried onto the <symbol>, because the source files set them on the root
    <svg> and the children inherit. Drop them and every icon renders as a
    black silhouette.

Idempotent: run it again after editing any source icon.

    python tools/build_icon_sprite.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

_NS = "http://www.w3.org/2000/svg"

#: Root attributes that must ride along to the <symbol> or the children lose
#: their styling. `currentColor` values are preserved verbatim, which is what
#: lets a CSS `color:` drive the icon.
_INHERIT = ("fill", "stroke", "stroke-width", "stroke-linecap",
            "stroke-linejoin", "stroke-miterlimit", "opacity")

#: Variants the operator asked to leave out of the sprite.
_SKIP = ("swaxs-reduction-alt-b", "swaxs-reduction-alt-c")


def build(src_dir: Path) -> tuple[str, list[str]]:
    ET.register_namespace("", _NS)
    parts, ids = [], []
    for path in sorted(src_dir.glob("*.svg")):
        icon_id = path.stem
        if icon_id in _SKIP:
            continue
        root = ET.fromstring(path.read_text())

        attrs = [f'id="{icon_id}"']
        vb = root.get("viewBox")
        attrs.append(f'viewBox="{vb}"' if vb else 'viewBox="0 0 24 24"')
        for a in _INHERIT:
            v = root.get(a)
            if v is not None:
                attrs.append(f'{a}="{v}"')

        body = "".join(
            ET.tostring(child, encoding="unicode").replace(f' xmlns="{_NS}"', "")
            for child in root
        ).strip()
        parts.append(f'  <symbol {" ".join(attrs)}>\n    {body}\n  </symbol>')
        ids.append(icon_id)

    sprite = (
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" '
        'aria-hidden="true">\n'
        "  <!-- Generated by tools/build_icon_sprite.py from\n"
        "       assets/icons/swaxs-icons-svg/. Do not edit by hand: edit the\n"
        "       source icon and re-run the script. -->\n"
        + "\n".join(parts)
        + "\n</svg>\n"
    )
    return sprite, ids


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    src = root / "assets" / "icons" / "swaxs-icons-svg"
    if not src.is_dir():
        print(f"✗ no icon source at {src}")
        return 1

    sprite, ids = build(src)
    if not ids:
        print("✗ no icons found — refusing to write an empty sprite")
        return 1

    # Two destinations, no more: the source of truth under assets/, and the
    # Jinja partial the hub inlines. A third copy in hub/static/ was tempting
    # (other apps could <use> it by URL) but it is one more thing to go stale,
    # and nothing needs it yet.
    for out in (root / "assets" / "icons" / "swaxs-icons-sprite.svg",
                root / "hub" / "templates" / "_icon_sprite.svg"):
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(sprite, encoding="utf-8")
        print(f"✓ wrote {out.relative_to(root)} ({out.stat().st_size:,} bytes)")

    # The tokens sheet has to travel with it, for the same static-folder reason.
    tokens = (root / "assets" / "icons" / "swaxs-tokens.css")
    if tokens.is_file():
        dst = root / "hub" / "static" / "swaxs-tokens.css"
        dst.write_text(tokens.read_text(), encoding="utf-8")
        print(f"✓ wrote {dst.relative_to(root)}")

    n_marks = _write_app_marks(root)
    n_sprites = _write_app_sprites(root, sprite)
    n_helpers = _write_icon_helpers(root)
    print(f"  {n_helpers} icon-helper partials (_icon_helpers.html)")
    print(f"  {len(ids)} symbols: {', '.join(ids[:4])} … {ids[-1]}")
    print(f"  {n_marks} per-app mark partials + token sheets")
    print(f"  {n_sprites} per-app full-sprite partials (for in-UI <use>)")
    return 0


def _write_app_sprites(root: Path, sprite: str) -> int:
    """The FULL sprite into each app's templates/_icon_sprite.svg.

    Distinct from _app_mark (one symbol, the app's own tab/card icon): once an
    app's own UI uses the shared glyphs — a folder icon on a folder button, a
    stop icon on Stop — it needs every symbol it references available to
    `<use href="#…">`, and `<use>` only resolves symbols in the SAME document.
    Flask serves each app from its own folder, so a <link> or URL <use> to the
    hub's copy 404s on port 5103; the sprite has to be inlined per app. The hub
    already inlines its own copy from hub/templates/_icon_sprite.svg — these are
    the same bytes for the other ten.
    """
    import yaml
    apps = yaml.safe_load((root / "apps.yml").read_text())["apps"]
    n = 0
    for a in apps:
        tpl_dir = root / a["id"] / "templates"
        if not tpl_dir.is_dir():
            continue
        (tpl_dir / "_icon_sprite.svg").write_text(sprite, encoding="utf-8")
        n += 1
    return n


#: Shared JS helpers, written next to every app's sprite partial and included
#: right after it. One source, so every app builds icons the same way and never
#: falls back to an emoji. setIco() puts dynamic text in a TEXT node, so a server
#: message (an error string, a file name) can never be parsed as HTML.
ICON_HELPERS = """<script>
/* Platform icon helpers (generated by tools/build_icon_sprite.py — do not edit). */
function icoSvg(n){return '<svg class="ico" aria-hidden="true"><use href="#swaxs-ui-'+n+'"/></svg>';}
function setIco(el,n,text){if(!el)return;el.innerHTML=icoSvg(n)+' ';el.appendChild(document.createTextNode(text==null?'':String(text)));}
/* Keep every open SWAXS tab on one theme: a toggle in any app is saved under the
   shared key, and the others follow through the storage event. */
window.addEventListener('storage',function(e){if(e.key!=='swaxs-theme'||!e.newValue)return;
  if(document.documentElement.getAttribute('data-theme')!==e.newValue&&typeof window.toggleTheme==='function')window.toggleTheme();});
/* Charts follow the theme too. swaxsPlotTheme() = current palette for a chart;
   swaxsRethemePlots() re-colours every Plotly chart on the page, and runs on its
   own whenever data-theme changes, so no app has to remember to redraw. */
function swaxsPlotTheme(){var c=getComputedStyle(document.documentElement),
  g=function(n,d){return (c.getPropertyValue(n)||'').trim()||d;};
  return {bg:g('--surface','#fff'),fg:g('--txt','#1f2937'),muted:g('--muted','#4b5563'),
    grid:g('--border','#e5e7eb'),line:g('--border-strong','#c3c9d1'),legend:g('--surface','#fff'),
    err:g('--err-text','#b91c1c'),accent:g('--accent','#B1040E')};}
function swaxsRethemePlots(){if(!window.Plotly)return;var T=swaxsPlotTheme();
  var clear=function(v){return !v||v==='transparent'||/rgba\([^)]*,\s*0\)/.test(String(v));};
  document.querySelectorAll('.js-plotly-plot').forEach(function(el){try{
    var L=el.layout||{},u={'font.color':T.fg,'title.font.color':T.fg,'legend.bgcolor':T.legend,'legend.bordercolor':T.grid};
    if(!clear(L.plot_bgcolor))u.plot_bgcolor=T.bg; if(!clear(L.paper_bgcolor))u.paper_bgcolor=T.bg;
    Object.keys(L).forEach(function(k){if(/^[xy]axis\d*$/.test(k)){u[k+'.gridcolor']=T.grid;u[k+'.linecolor']=T.line;u[k+'.color']=T.muted;}});
    window.Plotly.relayout(el,u);}catch(e){}});}
/* Carry the theme along on every link to another SWAXS app (hub Open buttons,
   ← Hub links): add ?theme=<current> just before the browser follows it. */
document.addEventListener('click',function(e){var a=e.target&&e.target.closest&&e.target.closest('a[href]');if(!a)return;
  try{var u=new URL(a.href,location.href);if(!/^(localhost|127\.0\.0\.1)$/.test(u.hostname)||u.port===location.port)return;
    u.searchParams.set('theme',document.documentElement.getAttribute('data-theme')||'light');a.href=u.toString();}catch(_){}},true);
/* Uniform top bar: apps without their own live status / project display carry
   the standard placeholders (#barStatus, #barProject); fill them from the app's
   own /api/health and /api/project so every bar shows the same information. */
(function(){
  function stat(){var el=document.getElementById('barStatus');if(!el)return;var t=el.querySelector('.bar-status-txt');
    fetch('/api/health',{cache:'no-store'}).then(function(r){el.classList.toggle('ok',r.ok);el.classList.toggle('down',!r.ok);
      if(t)t.textContent=r.ok?'Connected':'Offline';}).catch(function(){el.classList.remove('ok');el.classList.add('down');if(t)t.textContent='Offline';});}
  function proj(){var el=document.getElementById('barProject');if(!el)return;
    fetch('/api/project',{cache:'no-store'}).then(function(r){return r.ok?r.json():{};}).then(function(d){
      var p=(d&&(d.project_root||d.root||d.project))||'';el.textContent=p||'no project selected';
      el.title=p?('Project folder: '+p):'No project selected in the hub';}).catch(function(){});}
  function go(){stat();proj();setInterval(stat,5000);setInterval(proj,30000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',go);else go();
})();
/* Shared folder picker for every Browse… button: swaxsBrowse('inputId', after).
   Lists folders through the app's own GET /api/browse ({current,parent,dirs}),
   starts at the folder already typed (relative paths open inside the project),
   writes the chosen path into the input, fires its change event, then calls
   after() if given (e.g. the app's Set). Names go in as TEXT, never as HTML. */
function swaxsBrowse(id,after){var inp=document.getElementById(id);if(!inp)return;
  var bd=document.createElement('div');bd.className='swx-pick-bd';
  var m=document.createElement('div');m.className='swx-pick';m.setAttribute('role','dialog');m.setAttribute('aria-label','Choose a folder');
  m.innerHTML='<div class="swx-pick-hd"><b>Choose a folder</b><button type="button" class="swx-pick-x" aria-label="Close">'+icoSvg('close')+'</button></div>'
   +'<div class="swx-pick-path"><button type="button" class="btn btn-ghost btn-sm swx-up">\u2191 Up</button><input type="text" class="swx-cur" spellcheck="false"></div>'
   +'<div class="swx-pick-list"></div>'
   +'<div class="swx-pick-ft"><button type="button" class="btn btn-ghost btn-sm swx-can">Cancel</button><button type="button" class="btn btn-primary btn-sm swx-ok">Select this folder</button></div>';
  bd.appendChild(m);document.body.appendChild(bd);
  var cur=m.querySelector('.swx-cur'),list=m.querySelector('.swx-pick-list'),up=m.querySelector('.swx-up'),par=null;
  function close(){document.removeEventListener('keydown',key,true);bd.remove();}
  function key(e){if(e.key==='Escape'){e.stopPropagation();close();}}
  function load(path){list.textContent='Loading\u2026';
    fetch('/api/browse?path='+encodeURIComponent(path||''),{cache:'no-store'}).then(function(r){return r.json();}).then(function(d){
      cur.value=d.current||'';par=d.parent;up.disabled=!par;list.textContent='';
      (d.dirs||[]).forEach(function(n){var b=document.createElement('button');b.type='button';b.className='swx-dir';
        b.innerHTML=icoSvg('folder')+' ';b.appendChild(document.createTextNode(n));
        b.onclick=function(){load((d.current||'').replace(/[\\\/]+$/,'')+'/'+n);};
        list.appendChild(b);});
      if(!(d.dirs||[]).length){var e=document.createElement('div');e.className='swx-empty';e.textContent='No sub-folders here.';list.appendChild(e);}
    }).catch(function(){list.textContent='Could not list this folder.';});}
  m.querySelector('.swx-pick-x').onclick=close;m.querySelector('.swx-can').onclick=close;
  bd.addEventListener('mousedown',function(e){if(e.target===bd)close();});
  up.onclick=function(){if(par)load(par);};
  cur.addEventListener('keydown',function(e){if(e.key==='Enter'){e.preventDefault();load(cur.value);}});
  m.querySelector('.swx-ok').onclick=function(){inp.value=cur.value;close();
    inp.dispatchEvent(new Event('input',{bubbles:true}));inp.dispatchEvent(new Event('change',{bubbles:true}));
    if(typeof after==='function')after();};
  document.addEventListener('keydown',key,true);load(inp.value);}
if(window.MutationObserver)new MutationObserver(function(){swaxsRethemePlots();})
  .observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});
</script>
"""

#: Runs in <head>, before first paint, in EVERY app: one rule for the starting
#: theme everywhere — the saved choice (shared key `swaxs-theme`) wins, else the
#: OS preference. Setting it this early also removes the light→dark flash.
THEME_BOOT = """<script>
/* Platform theme boot (generated by tools/build_icon_sprite.py — do not edit). */
(function(){var d;try{
/* Each app runs on its own port, and the browser keeps saved settings per port,
   so a theme chosen in one app does not exist in another. Links between apps
   carry ?theme=…; adopt it here so moving between apps keeps the theme. */
var q=new URLSearchParams(location.search).get('theme');
if(q==='dark'||q==='light'){localStorage.setItem('swaxs-theme',q);}
var s=localStorage.getItem('swaxs-theme');
d=s?s==='dark':!!(window.matchMedia&&matchMedia('(prefers-color-scheme: dark)').matches);}catch(e){d=true;}
document.documentElement.setAttribute('data-theme',d?'dark':'light');})();
</script>
"""


def _write_icon_helpers(root: Path) -> int:
    """templates/_icon_helpers.html for the hub and every registered app."""
    import yaml
    apps = yaml.safe_load((root / "apps.yml").read_text())["apps"]
    n = 0
    for d in ["hub"] + [a["id"] for a in apps]:
        tpl_dir = root / d / "templates"
        if tpl_dir.is_dir():
            (tpl_dir / "_icon_helpers.html").write_text(ICON_HELPERS, encoding="utf-8")
            (tpl_dir / "_theme_boot.html").write_text(THEME_BOOT, encoding="utf-8")
            n += 1
    return n


def _write_app_marks(root: Path) -> int:
    """One self-contained `<svg>` per app, into `<app>/templates/_app_mark.svg`.

    An app needs exactly ONE symbol — its own — so inlining the whole 33-symbol
    sprite into all ten would be ten copies of 12 KB to draw one mark each.
    This writes just that app's art, as a complete <svg> with its
    `stroke="currentColor"` intact, so the template colours it with the accent
    token exactly as the hub card does.

    The token sheet is copied alongside, into each app's own static/, because
    Flask serves each app from its own folder and a <link> to the hub's copy
    would 404 on port 5103.
    """
    import yaml
    apps = yaml.safe_load((root / "apps.yml").read_text())["apps"]
    tokens = (root / "assets" / "icons" / "swaxs-tokens.css")
    src_dir = root / "assets" / "icons" / "swaxs-icons-svg"
    n = 0
    for a in apps:
        icon_id, app_id = a.get("icon_id"), a["id"]
        tpl_dir = root / app_id / "templates"
        if not icon_id or not tpl_dir.is_dir():
            continue
        raw = (src_dir / f"{icon_id}.svg").read_text()
        m = re.search(r"<svg\b([^>]*)>(.*)</svg>", raw, re.S)
        keep = " ".join(
            f'{k}="{v}"' for k, v in re.findall(r'([\w-]+)="([^"]*)"', m.group(1))
            if k in ("viewBox", "fill", "stroke", "stroke-width",
                     "stroke-linecap", "stroke-linejoin"))
        (tpl_dir / "_app_mark.svg").write_text(
            f'<!-- {app_id}: its own mark, the same artwork as its hub card and\n'
            f'     tab icon. Generated by tools/build_icon_sprite.py from\n'
            f'     assets/icons/swaxs-icons-svg/{icon_id}.svg — do not edit. -->\n'
            f'<svg class="app-mark" {keep} aria-hidden="true">'
            f'{m.group(2).strip()}</svg>\n', encoding="utf-8")
        if tokens.is_file():
            st = root / app_id / "static"
            st.mkdir(parents=True, exist_ok=True)
            (st / "swaxs-tokens.css").write_text(tokens.read_text(), encoding="utf-8")
        n += 1
    return n


if __name__ == "__main__":
    sys.exit(main())
