#!/usr/bin/env python3
"""
build_icon_sprite.py — one <symbol> sprite from assets/icons/swaxs-icons-svg/.

The icon set is a folder of standalone .svg files (35 at the time of
writing). The count is DISCOVERED by globbing, never listed here — adding an
icon means dropping the file in and re-running this. The hub references them as
`<svg><use href="…#swaxs-reduction"/></svg>`, which needs a single document of
<symbol> elements, so this builds it:

    assets/icons/swaxs-icons-svg/*.svg   →   assets/icons/swaxs-icons-sprite.svg
                                         →   hub/templates/_icon_sprite.svg

The hub serves its OWN static folder (Flask(__name__)), so a file under
assets/ is not reachable from a hub page. Same reason tools/make_watchdog_icon
copies its PNG there, and tests/test_favicons.py checks it.

What each symbol keeps and drops:

  * the file's `viewBox` becomes the symbol's — the set is drawn on 24x24, but
    it is read off the file rather than assumed, so an odd one out still works;
  * `width`/`height` are DROPPED. A symbol must size to its <use>, and a
    hard-coded 24px would make every instance 24px whatever the CSS says;
  * `fill`, `stroke`, `stroke-width`, `stroke-linecap`, `stroke-linejoin` are
    carried onto the <symbol>, because the source files set them on the root
    <svg> and the children inherit. Drop them and every icon renders as a
    black silhouette.

Idempotent: run it again after editing any source icon.

    python tools/build_icon_sprite.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET

_NS = "http://www.w3.org/2000/svg"

#: Root attributes that must ride along to the <symbol> or the children lose
#: their styling. `currentColor` values are preserved verbatim, which is what
#: lets a CSS `color:` drive the icon.
_INHERIT = ("fill", "stroke", "stroke-width", "stroke-linecap",
            "stroke-linejoin", "stroke-miterlimit", "opacity")

#: Variants the operator asked to leave out of the sprite.
_SKIP = ("swaxs-reduction-alt-b", "swaxs-reduction-alt-c")


def build(src_dir: Path) -> tuple[str, list[str]]:
    ET.register_namespace("", _NS)
    parts, ids = [], []
    for path in sorted(src_dir.glob("*.svg")):
        icon_id = path.stem
        if icon_id in _SKIP:
            continue
        root = ET.fromstring(path.read_text())

        attrs = [f'id="{icon_id}"']
        vb = root.get("viewBox")
        attrs.append(f'viewBox="{vb}"' if vb else 'viewBox="0 0 24 24"')
        for a in _INHERIT:
            v = root.get(a)
            if v is not None:
                attrs.append(f'{a}="{v}"')

        body = "".join(
            ET.tostring(child, encoding="unicode").replace(f' xmlns="{_NS}"', "")
            for child in root
        ).strip()
        parts.append(f'  <symbol {" ".join(attrs)}>\n    {body}\n  </symbol>')
        ids.append(icon_id)

    sprite = (
        '<svg xmlns="http://www.w3.org/2000/svg" style="display:none" '
        'aria-hidden="true">\n'
        "  <!-- Generated by tools/build_icon_sprite.py from\n"
        "       assets/icons/swaxs-icons-svg/. Do not edit by hand: edit the\n"
        "       source icon and re-run the script. -->\n"
        + "\n".join(parts)
        + "\n</svg>\n"
    )
    return sprite, ids


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    src = root / "assets" / "icons" / "swaxs-icons-svg"
    if not src.is_dir():
        print(f"✗ no icon source at {src}")
        return 1

    sprite, ids = build(src)
    if not ids:
        print("✗ no icons found — refusing to write an empty sprite")
        return 1

    # Two destinations, no more: the source of truth under assets/, and the
    # Jinja partial the hub inlines. A third copy in hub/static/ was tempting
    # (other apps could <use> it by URL) but it is one more thing to go stale,
    # and nothing needs it yet.
    for out in (root / "assets" / "icons" / "swaxs-icons-sprite.svg",
                root / "hub" / "templates" / "_icon_sprite.svg"):
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(sprite, encoding="utf-8")
        print(f"✓ wrote {out.relative_to(root)} ({out.stat().st_size:,} bytes)")

    # The tokens sheet has to travel with it, for the same static-folder reason.
    tokens = (root / "assets" / "icons" / "swaxs-tokens.css")
    if tokens.is_file():
        dst = root / "hub" / "static" / "swaxs-tokens.css"
        dst.write_text(tokens.read_text(), encoding="utf-8")
        print(f"✓ wrote {dst.relative_to(root)}")

    n_marks = _write_app_marks(root)
    print(f"  {len(ids)} symbols: {', '.join(ids[:4])} … {ids[-1]}")
    print(f"  {n_marks} per-app mark partials + token sheets")
    return 0


def _write_app_marks(root: Path) -> int:
    """One self-contained `<svg>` per app, into `<app>/templates/_app_mark.svg`.

    An app needs exactly ONE symbol — its own — so inlining the whole 33-symbol
    sprite into all ten would be ten copies of 12 KB to draw one mark each.
    This writes just that app's art, as a complete <svg> with its
    `stroke="currentColor"` intact, so the template colours it with the accent
    token exactly as the hub card does.

    The token sheet is copied alongside, into each app's own static/, because
    Flask serves each app from its own folder and a <link> to the hub's copy
    would 404 on port 5103.
    """
    import yaml
    apps = yaml.safe_load((root / "apps.yml").read_text())["apps"]
    tokens = (root / "assets" / "icons" / "swaxs-tokens.css")
    src_dir = root / "assets" / "icons" / "swaxs-icons-svg"
    n = 0
    for a in apps:
        icon_id, app_id = a.get("icon_id"), a["id"]
        tpl_dir = root / app_id / "templates"
        if not icon_id or not tpl_dir.is_dir():
            continue
        raw = (src_dir / f"{icon_id}.svg").read_text()
        m = re.search(r"<svg\b([^>]*)>(.*)</svg>", raw, re.S)
        keep = " ".join(
            f'{k}="{v}"' for k, v in re.findall(r'([\w-]+)="([^"]*)"', m.group(1))
            if k in ("viewBox", "fill", "stroke", "stroke-width",
                     "stroke-linecap", "stroke-linejoin"))
        (tpl_dir / "_app_mark.svg").write_text(
            f'<!-- {app_id}: its own mark, the same artwork as its hub card and\n'
            f'     tab icon. Generated by tools/build_icon_sprite.py from\n'
            f'     assets/icons/swaxs-icons-svg/{icon_id}.svg — do not edit. -->\n'
            f'<svg class="app-mark" {keep} aria-hidden="true">'
            f'{m.group(2).strip()}</svg>\n', encoding="utf-8")
        if tokens.is_file():
            st = root / app_id / "static"
            st.mkdir(parents=True, exist_ok=True)
            (st / "swaxs-tokens.css").write_text(tokens.read_text(), encoding="utf-8")
        n += 1
    return n


if __name__ == "__main__":
    sys.exit(main())
